"""
Code generation from SymPy expressions to Modelica, C, and NumPy.

These are the final step of the derivation pipeline. Every equation
in OPAL's Modelica library and C++ solver is generated by these functions,
not hand-written.
"""

import sympy as sp
from sympy.printing.c import C99CodePrinter
from sympy.utilities.lambdify import lambdify
import textwrap


class ModelicaPrinter(sp.printing.StrPrinter):
    """
    Prints SymPy expressions as Modelica code.

    Differences from default SymPy printer:
    - Power uses ^ not ** (Modelica convention... actually Modelica uses ^ for XOR
      and ** for power. We use ** .)
    - Actually Modelica uses the same ** as Python for exponentiation.
    - Indexed variables use [] not ()
    - Boolean constants: true/false not True/False
    """

    def _print_Pow(self, expr):
        base = self._print(expr.base)
        exp = self._print(expr.exp)
        # Modelica uses x^y for power... no, Modelica uses x^y.
        # Actually: Modelica uses x ^ y for exponentiation.
        if expr.exp == sp.Rational(1, 2):
            return f"sqrt({base})"
        if expr.exp == -1:
            return f"(1.0 / {base})"
        return f"({base}) ^ ({exp})"

    def _print_Indexed(self, expr):
        base = self._print(expr.base)
        indices = ", ".join(self._print(idx) for idx in expr.indices)
        return f"{base}[{indices}]"

    def _print_Float(self, expr):
        return str(float(expr))

    def _print_Rational(self, expr):
        return f"({expr.p}.0 / {expr.q}.0)"


def to_modelica(expr, varname=None, comment=None):
    """
    Convert a SymPy expression to a Modelica equation string.

    Args:
        expr: SymPy expression (the RHS)
        varname: optional LHS variable name. If provided, returns "varname = expr;"
        comment: optional comment to prepend

    Returns:
        String of Modelica code.

    Example:
        >>> import sympy as sp
        >>> x, y = sp.symbols('x y')
        >>> to_modelica(x**2 + 2*y, varname='result')
        'result = (x) ^ (2) + 2*y;'
    """
    printer = ModelicaPrinter()
    rhs = printer.doprint(expr)

    lines = []
    if comment:
        lines.append(f"  // {comment}")
    if varname:
        lines.append(f"  {varname} = {rhs};")
    else:
        lines.append(f"  {rhs}")

    return "\n".join(lines)


def to_modelica_block(equations, header_comment=None, source_script=None):
    """
    Convert multiple equations to a Modelica equation block.

    Args:
        equations: list of (varname, expr) tuples or (varname, expr, comment) tuples
        header_comment: comment at top of block
        source_script: derivation script path for traceability

    Returns:
        String of Modelica equation block.
    """
    lines = []
    if source_script:
        lines.append(f"  // Generated by: {source_script}")
        lines.append(f"  // Do not edit by hand.")
    if header_comment:
        lines.append(f"  // {header_comment}")
    if lines:
        lines.append("")

    for eq in equations:
        if len(eq) == 3:
            varname, expr, comment = eq
            lines.append(to_modelica(expr, varname=varname, comment=comment))
        else:
            varname, expr = eq
            lines.append(to_modelica(expr, varname=varname))

    return "\n".join(lines)


def to_c(expr, funcname, args, return_type="double"):
    """
    Convert a SymPy expression to a C function.

    Args:
        expr: SymPy expression to evaluate
        funcname: C function name
        args: list of SymPy symbols that become function arguments
        return_type: C return type (default "double")

    Returns:
        String of C function code.
    """
    printer = C99CodePrinter()
    body = printer.doprint(expr)

    arg_str = ", ".join(f"double {printer.doprint(a)}" for a in args)

    return textwrap.dedent(f"""\
        {return_type} {funcname}({arg_str}) {{
            return {body};
        }}
    """)


def to_c_block(expressions, funcname, args, return_names=None):
    """
    Convert multiple expressions to a C function that computes all of them.

    Args:
        expressions: list of SymPy expressions
        funcname: C function name
        args: list of input SymPy symbols
        return_names: list of output variable names (same length as expressions)

    Returns:
        C function that writes results to output pointer array.
    """
    printer = C99CodePrinter()
    arg_str = ", ".join(f"double {printer.doprint(a)}" for a in args)

    lines = [f"void {funcname}({arg_str}, double* out) {{"]
    for idx, expr in enumerate(expressions):
        body = printer.doprint(expr)
        name = return_names[idx] if return_names else f"out[{idx}]"
        lines.append(f"    out[{idx}] = {body};  // {name}")
    lines.append("}")

    return "\n".join(lines)


def to_numpy(expr, args):
    """
    Convert a SymPy expression to a callable NumPy function.

    Args:
        expr: SymPy expression
        args: list of SymPy symbols (function arguments, in order)

    Returns:
        A callable Python function using NumPy for evaluation.

    Example:
        >>> import sympy as sp
        >>> x, y = sp.symbols('x y')
        >>> f = to_numpy(x**2 + y, [x, y])
        >>> f(3.0, 1.0)
        10.0
    """
    return lambdify(args, expr, modules="numpy")


def to_numpy_multi(expressions, args, return_names=None):
    """
    Convert multiple expressions to a single callable that returns a dict.

    Args:
        expressions: list of (name, expr) tuples
        args: list of SymPy symbols

    Returns:
        Callable that returns dict of {name: value}.
    """
    funcs = {name: lambdify(args, expr, modules="numpy") for name, expr in expressions}

    def evaluator(*values):
        return {name: f(*values) for name, f in funcs.items()}

    return evaluator
