#!/usr/bin/env python3
"""
OPAL Feasibility Test 4 — Equation Count Scaling
=================================================
Measures how extraction time and equation count grow with model size.

Uses ScalablePipe.mo: an N-cell 1D pipe with 2 ODEs + 1 algebraic per cell.
Tests N = 1, 5, 10, 20 in separate OMC sessions to avoid cache effects.

Metrics:
  - Equation count (flat, backEnd) vs N
  - State count vs N
  - BLT block count vs N
  - Extraction time (instantiate, flat, backEnd) vs N
  - Does BLT block count scale linearly?

Run:
    ../external/venv/bin/python test4_scale.py
"""

import sys
import time
import xml.etree.ElementTree as ET
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from extraction_utils import (
    RESULTS_DIR, MODELS_DIR, OPAL_ROOT,
    start_omc_session, omc_check, dump_xml_dae,
    parse_xml_report, write_tabular_report,
)

N_VALUES = [1, 5, 10, 20]

# ScalablePipe is parameterised by N, but OM can't re-parameterise between calls.
# We generate N-specific model files dynamically from the base template.
TEMPLATE = """
// Auto-generated for Test 4, N={N}
model ScalablePipeN{N}
  "ScalablePipe with N={N} cells (generated by test4_scale.py)"

  parameter Integer N    = {N};
  parameter Real    R    = 1e4;
  parameter Real    C    = 1e-9;
  parameter Real    rho  = 720.0;
  parameter Real    Cp   = 5000.0;
  parameter Real    V    = 0.01;
  parameter Real    p_in  = 15.5e6;
  parameter Real    p_out = 15.4e6;
  parameter Real    T_in  = 563.0;

  Real p[N](each start = 15.5e6, each fixed = true);
  Real T[N](each start = 563.0,  each fixed = true);
  Real mdot[N+1];

equation
  p_in - p[1] = R * mdot[1];
  for i in 1:N-1 loop
    p[i] - p[i+1] = R * mdot[i+1];
  end for;
  p[N] - p_out = R * mdot[N+1];

  for i in 1:N loop
    C * der(p[i]) = mdot[i] - mdot[i+1];
    rho * V * Cp * der(T[i]) =
      mdot[i]   * Cp * (T_in - T[i])
    - mdot[i+1] * Cp * T[i];
  end for;

end ScalablePipeN{N};
"""


def run_scale_point(N: int) -> dict:
    """
    Run all extraction steps for ScalablePipeN{N} in a fresh OMC session.
    Returns a metrics dict.
    """
    model_name = f"ScalablePipeN{N}"
    print(f"\n  N={N}: generating model …")

    # Write the N-specific model file
    mo_path = RESULTS_DIR / f"scale_N{N}.mo"
    mo_path.write_text(TEMPLATE.format(N=N))

    omc = start_omc_session(load_msl=False)
    metrics = {"N": N}

    try:
        # Load
        t0 = time.perf_counter()
        omc.sendExpression(f'loadFile("{mo_path.as_posix()}")', parsed=False)
        omc_check(omc, f"loadFile N={N}")
        metrics["t_load"] = time.perf_counter() - t0

        # instantiateModel (flattening)
        t0 = time.perf_counter()
        flat_mo = omc.sendExpression(f"instantiateModel({model_name})", parsed=False)
        omc_check(omc, f"instantiateModel N={N}")
        metrics["t_instantiate"] = time.perf_counter() - t0
        metrics["flat_mo_lines"] = flat_mo.count("\\n") + flat_mo.count("\n")

        # dumpXMLDAE flat
        t0 = time.perf_counter()
        _, info_flat = dump_xml_dae(
            omc, model_name, "flat", f"scale_N{N}_flat"
        )
        metrics["t_flat"] = time.perf_counter() - t0
        metrics.update({
            "eqs_flat":   info_flat.get("n_equations"),
            "vars_flat":  info_flat.get("n_ordered_vars"),
        })

        # dumpXMLDAE backEnd
        t0 = time.perf_counter()
        xml_path, info_back = dump_xml_dae(
            omc, model_name, "backEnd", f"scale_N{N}_backEnd"
        )
        metrics["t_backend"] = time.perf_counter() - t0
        metrics.update({
            "eqs_back":   info_back.get("n_equations"),
            "vars_back":  info_back.get("n_ordered_vars"),
            "states":     info_back.get("n_states"),
            "blt_blocks": info_back.get("n_blt_blocks"),
            "loop_blocks":info_back.get("n_loop_blocks"),
        })

        # BLT block size distribution
        root = ET.parse(xml_path).getroot()
        blt_sizes = [len(list(b)) for b in root.findall(".//bltBlock")]
        if blt_sizes:
            metrics["max_blt_block_size"] = max(blt_sizes)
            metrics["blt_size_dist"] = {s: blt_sizes.count(s) for s in set(blt_sizes)}

        print(f"    eqs(flat/back)={metrics.get('eqs_flat')}/{metrics.get('eqs_back')}  "
              f"states={metrics.get('states')}  BLT={metrics.get('blt_blocks')}  "
              f"time(inst+flat+back)="
              f"{metrics.get('t_instantiate',0):.2f}+"
              f"{metrics.get('t_flat',0):.2f}+"
              f"{metrics.get('t_backend',0):.2f}s")

    finally:
        omc.sendExpression("quit()", parsed=False)

    return metrics


def main() -> int:
    print("=" * 70)
    print("OPAL Feasibility Test 4 — Equation Count Scaling")
    print("=" * 70)

    all_metrics = []
    for N in N_VALUES:
        try:
            m = run_scale_point(N)
            all_metrics.append(m)
        except Exception as e:
            print(f"  ERROR for N={N}: {e}")
            all_metrics.append({"N": N, "error": str(e)})

    # ------------------------------------------------------------------
    # Print scaling table
    # ------------------------------------------------------------------
    print(f"\n{'='*70}")
    print("Scaling summary:")
    hdr = (f"  {'N':>4}  {'Eqs(flat)':>10}  {'Eqs(back)':>10}  "
           f"{'States':>7}  {'BLTblks':>8}  {'MaxBlk':>7}  "
           f"{'t_inst':>7}  {'t_flat':>7}  {'t_back':>7}")
    print(hdr)
    print("  " + "-" * (len(hdr) - 2))
    for m in all_metrics:
        if "error" in m:
            print(f"  {m['N']:>4}  ERROR: {m['error'][:50]}")
            continue
        print(
            f"  {m['N']:>4}  "
            f"{str(m.get('eqs_flat', '?')):>10}  "
            f"{str(m.get('eqs_back', '?')):>10}  "
            f"{str(m.get('states', '?')):>7}  "
            f"{str(m.get('blt_blocks', '?')):>8}  "
            f"{str(m.get('max_blt_block_size', '?')):>7}  "
            f"{m.get('t_instantiate', 0):>7.2f}  "
            f"{m.get('t_flat', 0):>7.2f}  "
            f"{m.get('t_backend', 0):>7.2f}"
        )

    # Linearity check
    findings = []
    valid = [m for m in all_metrics if "error" not in m and m.get("eqs_back") is not None]
    if len(valid) >= 2:
        n1, n2 = valid[0], valid[-1]
        eq_ratio = n2["eqs_back"] / n1["eqs_back"] if n1["eqs_back"] else None
        n_ratio  = n2["N"] / n1["N"]
        if eq_ratio:
            linear = abs(eq_ratio / n_ratio - 1.0) < 0.15  # within 15% of linear
            findings.append(
                f"Equation scaling: {n1['eqs_back']} eqs @ N={n1['N']} → "
                f"{n2['eqs_back']} eqs @ N={n2['N']}  "
                f"(ratio={eq_ratio:.2f}, N ratio={n_ratio:.1f}) → "
                f"{'LINEAR' if linear else 'SUPER-LINEAR'}"
            )
        t_ratio = (n2.get("t_backend", 0)) / max(n1.get("t_backend", 0.001), 0.001)
        findings.append(
            f"BackEnd time scaling: {n1.get('t_backend', 0):.2f}s → "
            f"{n2.get('t_backend', 0):.2f}s  (ratio={t_ratio:.1f}×)"
        )

    # Write report
    from datetime import datetime
    lines = []
    lines.append("OPAL Feasibility Test 4 — Equation Count Scaling")
    lines.append(f"Run : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("")
    lines.append(hdr)
    lines.append("  " + "-" * (len(hdr) - 2))
    for m in all_metrics:
        if "error" in m:
            lines.append(f"  {m['N']:>4}  ERROR: {m['error'][:50]}")
            continue
        lines.append(
            f"  {m['N']:>4}  "
            f"{str(m.get('eqs_flat', '?')):>10}  "
            f"{str(m.get('eqs_back', '?')):>10}  "
            f"{str(m.get('states', '?')):>7}  "
            f"{str(m.get('blt_blocks', '?')):>8}  "
            f"{str(m.get('max_blt_block_size', '?')):>7}  "
            f"{m.get('t_instantiate', 0):>7.2f}  "
            f"{m.get('t_flat', 0):>7.2f}  "
            f"{m.get('t_backend', 0):>7.2f}"
        )
    lines += ["", "Findings:", *[f"  {f}" for f in findings]]
    lines += [
        "",
        "Decision criteria (FM4):",
        "  PASS: equation count linear in N, backEnd time ≤ 2× linear → proceed",
        "  WARN: super-linear time → may need to extract before index reduction",
        "  FAIL: extraction fails for large N → vessel must be external C++",
    ]

    report_path = RESULTS_DIR / "test4_report.txt"
    text = "\n".join(lines) + "\n"
    report_path.write_text(text)
    print(f"\n{text}\nReport → {report_path}")

    n_fail = sum(1 for m in all_metrics if "error" in m)
    return 0 if n_fail == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
